### ISSUE TITLE
Virtio-Net driver is not respecting VIRTIO_NET_F_MRG_RXBUF

### ISSUE THREAD

**Issue by ddaney-fungible** [virtio-win/kvm-guest-drivers-windows#1090]
If a Virtio-Net PCI function (Device) does not advertise the VIRTIO_NET_F_MRG_RXBUF then the driver must supply a single descriptor RX buffer large enough to contain the virtio_net_hdr and the RX packet contents.

The Windows driver does not do this, it supplies a two descriptor buffer, one for the virtio_net_hdr and another for the packet contents, this behavior is explicitly prohibited by the specification.

**Comment by YanVugenfirer** [comment]
Related: 

- https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1089
- https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1078

**Comment by YanVugenfirer** [comment]
I think this is an unfortunate remnant of the support for the pre-1.0 virtio spec.

**Comment by ybendito** [comment]
Probably was broken long time ago. Probably the driver should fail to start if this feature is not present until this is fixed. Thank you for pointing this out.

**Comment by YanVugenfirer** [comment]
@ddaney-fungible Out of curiosity - do you experience issues with the non-compliant driver on HW or other than QEMU\KVM hypervisor?

**Comment by ddaney-fungible** [comment]
> @ddaney-fungible Out of curiosity - do you experience issues with the non-compliant driver on HW or other than QEMU\KVM hypervisor?

Yes. The failure was seen in a virtio-net function that is not part of Qemu. On the system in question EDK2 and Linux drivers seem to work well, but it was observed that this Windows driver was supplying buffers in two chunks, one of size 12 for the header and the second for the packet payload.

**Comment by ybendito** [comment]
@ddaney-fungible Can you please share with us the host features as suggested during feature negotiation? (better in hex)
Thanks.

**Comment by ddaney-fungible** [comment]
> @ddaney-fungible Can you please share with us the host features as suggested during feature negotiation? (better in hex) Thanks.

device_feature[0] = 0x00010029
defice_feature[1] = 0x00000057

Driver is responding with:

driver_feature[0] = 0x00010029
driver_feature[1] = 0x00000007

**Comment by ddaney-fungible** [comment]
I think there is a misunderstanding of how to interpret those values.

device_feature[0] = VIRTIO_NET_F_CSUM |
                                VIRTIO_NET_F_MTU |
                                VIRTIO_NET_F_MAC |
                                VIRTIO_NET_F_STATUS

device_feature[1] = VIRTIO_F_VERSION_1 |
                                VIRTIO_F_NOTIFICATION_DATA |
                                VIRTIO_F_ACCESS_PLATFORM |
                                VIRTIO_F_ORDER_PLATFORM |
                                VIRTIO_F_RING_PACKED

**Comment by ybendito** [comment]
@ddaney-fungible Sorry, by mistake I swapped them when read

**Comment by ybendito** [comment]
The [virtio  spec](https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.pdf) says:
**5.1.6.3.1 Driver Requirements: Setting Up Receive Buffers**
• If VIRTIO_NET_F_MRG_RXBUF is not negotiated:
– If VIRTIO_NET_F_GUEST_TSO4, VIRTIO_NET_F_GUEST_TSO6 or VIRTIO_NET_F_GUEST_-
UFO are negotiated, the driver SHOULD populate the receive queue(s) with buffers of at least
65562 bytes.
– Otherwise, the driver SHOULD populate the receive queue(s) with buffers of at least 1526 bytes.
• If VIRTIO_NET_F_MRG_RXBUF is negotiated, each buffer MUST be at least the size of the struct
virtio_net_hdr.
**Note: Obviously each buffer can be split across multiple descriptor elements.**
If VIRTIO_NET_F_MQ is negotiated, each of receiveq1.. .receiveqN that will be used SHOULD be populated
with receive buffers.
**5.1.6.3.2 Device Requirements: Setting Up Receive Buffers**
The device MUST set num_buffers to the number of descriptors used to hold the incoming packet.
The device MUST use only a single descriptor if VIRTIO_NET_F_MRG_RXBUF was not negotiated.
Note: This means that num_buffers will always be 1 if VIRTIO_NET_F_MRG_RXBUF is not negotiated.

In the terminology of the spec the "descriptor" is one or more "descriptor elements", combined together using VIRTQ_DESC_F_NEXT, see "2.8.6 Next Flag: Descriptor Chaining" (in the indirect area, if supported, or several consecutive elements in the descriptor queue)

The point of VIRTIO_NET_F_MRG_RXBUF is that this virtio-net specific feature allows to place a network packet over several consecutive descriptors (not chained together with VIRTQ_DESC_F_NEXT). 
Chaining the "descriptor elements" into one "descriptor" is virtio transport feature, common for all the virtio devices.

Probably this is a good idea to reduce number of descriptor elements and we'll evaluate the possibility to do so, but I think there is no violation of the spec. We can request the comment from virtio-comment or virtio-dev mail lists if needed.

**Comment by YanVugenfirer** [comment]
@ddaney-fungible I am wondering if you support RSS in your HW and if you aware of the virtio spec parts related to RSS. 
Also, it will be interesting to hear about the offload support.
