### ISSUE TITLE
vioserial driver can not work in windows_10_version_1703_x86 with cpu Intel(R) Xeon(R) Gold 6161

### ISSUE THREAD

**Issue by zhouwjfi** [virtio-win/kvm-guest-drivers-windows#297]
Hi all,

I found this commit 5c64ff04ac(Vioserial: Enable WPP tracing for Win7+) of vioserial driver may lead qemu-guest-agent fail to work. At that time, the channel status in libvirt is disconnected. 

Some more tests show that the situation only occurs in windows_10_version_1703_x86. 
I'm not sure if it is related with cpu Intel(R) Xeon(R) Gold 6161. In another machine of different hardware, it seems everything goes well.

I haven't got the reason. Do you have any ideas?

Thanks
Zhou

**Comment by YanVugenfirer** [comment]
Hi,
 
WPP should not be affecting functionality or be affected by CPU. But we definitely will have a loot.
What comes to my mind now (due to CPU and 32bits of the guest) is the following bug: https://bugzilla.redhat.com/show_bug.cgi?id=1515663

The solution is to provide -xsave flag to CPU command parameter in QEMU.

Best regards,
Yan.

**Comment by zhouwjfi** [comment]
Hi Yan,

Thanks for your quick reply which really helps me a lot!
When disable xsave flag, everything is Ok.
Thanks again!

Best regards,
Zhou

**Comment by YanVugenfirer** [comment]
Hi Zhou,

I am glad to hear that everything worked out!

Best regards,
Yan.
