### ISSUE TITLE
[viostor] try fix feature VIRTIO_BLK_F_SEG_MAX and VIRTIO_BLK_F_SIZE_MAX mishandling

### ISSUE THREAD

**Issue by icessspark** [virtio-win/kvm-guest-drivers-windows#692]
Problem:
When VirtIO Backend providing both `VIRTIO_BLK_F_SEG_MAX` and `VIRTIO_BLK_F_SIZE_MAX` features, the viostor failed to 
behave as expected.

Expected behavior:
The IO requests conveyed by viostor contains segments no more than `virtio_blk_config->seg_max` and the length of each segment is no longer than `virtio_blk_config->size_max`.

Practical situation：
VirtIO Backend has to process segment with larger `len`.

Evironment:
Host: Linux n248-180-131 4.19.117.bsk.6-amd64 #4.19.117.bsk.6 SMP Debian 4.19.117.bsk.6 Mon Jan 4 07:25:51 UTC x86_64 GNU/Linux

QEMU: QEMU emulator version 6.0.1 (v6.0.1-dirty), commit 9654e55a747575e2dafbb235a15645c0a48b08c4, which was partially revised to provide both `VIRTIO_BLK_F_SEG_MAX` and `VIRTIO_BLK_F_SIZE_MAX` feature:
```
diff --git a/hw/block/virtio-blk.c b/hw/block/virtio-blk.c
index d28979efb8..c342638728 100644
--- a/hw/block/virtio-blk.c
+++ b/hw/block/virtio-blk.c
@@ -932,8 +932,9 @@ static void virtio_blk_update_config(VirtIODevice *vdev, uint8_t *config)
     blk_get_geometry(s->blk, &capacity);
     memset(&blkcfg, 0, sizeof(blkcfg));
     virtio_stq_p(vdev, &blkcfg.capacity, capacity);
-    virtio_stl_p(vdev, &blkcfg.seg_max,
-                 s->conf.seg_max_adjust ? s->conf.queue_size - 2 : 128 - 2);
+    // virtio_stl_p(vdev, &blkcfg.seg_max,
+    //              s->conf.seg_max_adjust ? s->conf.queue_size - 2 : 128 - 2);
+    virtio_stl_p(vdev, &blkcfg.seg_max, 126);
     virtio_stw_p(vdev, &blkcfg.geometry.cylinders, conf->cyls);
     virtio_stl_p(vdev, &blkcfg.blk_size, blk_size);
     virtio_stw_p(vdev, &blkcfg.min_io_size, conf->min_io_size / blk_size);
@@ -956,7 +957,8 @@ static void virtio_blk_update_config(VirtIODevice *vdev, uint8_t *config)
     } else {
         blkcfg.geometry.sectors = conf->secs;
     }
-    blkcfg.size_max = 0;
+    // blkcfg.size_max = 0;
+    blkcfg.size_max = 4096;
     blkcfg.physical_block_exp = get_physical_block_exp(conf);
     blkcfg.alignment_offset = 0;
     blkcfg.wce = blk_enable_write_cache(s->blk);
@@ -1007,6 +1009,7 @@ static uint64_t virtio_blk_get_features(VirtIODevice *vdev, uint64_t features,
     features |= s->host_features;
 
     virtio_add_feature(&features, VIRTIO_BLK_F_SEG_MAX);
+    virtio_add_feature(&features, VIRTIO_BLK_F_SIZE_MAX);
     virtio_add_feature(&features, VIRTIO_BLK_F_GEOMETRY);
     virtio_add_feature(&features, VIRTIO_BLK_F_TOPOLOGY);
     virtio_add_feature(&features, VIRTIO_BLK_F_BLK_SIZE);
```
```
# QEMU launch cmd:
./qemu/build/x86_64-softmmu/qemu-system-x86_64 \
    --enable-kvm \
    -drive if=pflash,format=raw,file=/usr/share/ovmf/OVMF.fd \
    -device virtio-blk-pci,drive=drive-virtio-disk0,id=virtio-disk0,disable-legacy=on,packed=true,indirect_desc=off \
    -drive file=$1,if=none,id=drive-virtio-disk0 \
    -m 4G -smp 4 \
    -vnc :1
```
Guest: 
windows server 2016 or any other version with viostor support.

Possible solution:
The problem seems to take place in viostor/virtio_stor.c: VirtIoFindAdapter
When get `ConfigInfo->NumberOfPhysicalBreaks`, which seems to be exactly what seg_max is stand for, was not taken into consideration and `queueLength / 4` is applied instead.
Then, `ConfigInfo->MaximumTransferLength` is calculated through `ConfigInfo->NumberOfPhysicalBreaks` and `PAGE_SIZE`.
In our opinion, `PAGE_SIZE` should be `adaptExt->info.seg_max` acquired through `VIRTIO_BLK_F_SIZE_MAX` feature, which means the max size allowed for every segment.
In that case, we get `MaximumTransferLength` through `seg_max` multiplying `size_max` which makes much more sense in our own experience.
 
The problem is, no one of us is familiar with Windows driver developing and it is awkward for us to validate the exact fixup shown below. We really appreciate it if anyone could validate such fixeup through QEMU with the same revision and give out a detailed report. It would really help!
```
index f152229a..ac3aec7b 100755
--- a/viostor/virtio_stor.c
+++ b/viostor/virtio_stor.c
@@ -472,11 +472,14 @@ VirtIoFindAdapter(
     if(adaptExt->indirect) {
         adaptExt->queue_depth = queueLength;
     } else {
-        ConfigInfo->NumberOfPhysicalBreaks = max(SCSI_MINIMUM_PHYSICAL_BREAKS, (queueLength / 4));
+        // ConfigInfo->NumberOfPhysicalBreaks = max(SCSI_MINIMUM_PHYSICAL_BREAKS, (queueLength / 4));
+        ConfigInfo->NumberOfPhysicalBreaks = max(SCSI_MINIMUM_PHYSICAL_BREAKS, 
+            adaptExt->info.seg_max < queueLength && adaptExt->info.seg_max > 0 ? adaptExt->info.seg_max : (queueLength / 4) );
         adaptExt->queue_depth = max(((queueLength / ConfigInfo->NumberOfPhysicalBreaks) - 1), 1);
     }
 
-    ConfigInfo->MaximumTransferLength = ConfigInfo->NumberOfPhysicalBreaks * PAGE_SIZE;
+    // ConfigInfo->MaximumTransferLength = ConfigInfo->NumberOfPhysicalBreaks * PAGE_SIZE;
+    ConfigInfo->MaximumTransferLength = ConfigInfo->NumberOfPhysicalBreaks * adaptExt->info.size_max;
     ConfigInfo->NumberOfPhysicalBreaks++;
     adaptExt->max_tx_length = ConfigInfo->MaximumTransferLength;
```

**Comment by icessspark** [comment]
@vrozenfe Is there any progress here？

**Comment by vrozenfe** [comment]
@icessspark 

sorry for delay in response.

I have a couple of questions to you.
- the qemu part. was it submitted upstream and accepted by virtio-blk maintainers? I personally have some doubts about  these changes but this part needs to be reviewed by qemu community. 

Guest part. 
- ConfigInfo->NumberOfPhysicalBreaks = max(SCSI_MINIMUM_PHYSICAL_BREAKS, (queueLength / 4)); 
the idea was to make sure that virtio queue is capable to handle at least three requests simultaneously. (one processing
by qemu backend and two  slots more that are available for request (SRB) submission.    

+        ConfigInfo->NumberOfPhysicalBreaks = max(SCSI_MINIMUM_PHYSICAL_BREAKS, 
+            adaptExt->info.seg_max < queueLength && adaptExt->info.seg_max > 0 ? adaptExt->info.seg_max : (queueLength / 4) );

How it is going to work in the case when  adaptExt->info.seg_max == queueLength - 1 ? did you check this condition?
What are the performance results?

-    ConfigInfo->MaximumTransferLength = ConfigInfo->NumberOfPhysicalBreaks * PAGE_SIZE;
+    // ConfigInfo->MaximumTransferLength = ConfigInfo->NumberOfPhysicalBreaks * PAGE_SIZE;
+    ConfigInfo->MaximumTransferLength = ConfigInfo->NumberOfPhysicalBreaks * adaptExt->info.size_max;

to the best of my knowledge, on Windows ARM64/x64/x86 PAGE_SIZE is always 4K
DMA operates with the 4K pages . The meaning of MaximumTransferLength is the maximum DMA transfer 
and the meaning of NumberOfPhysicalBreaks is the maximum number of elements in SGList (kind of 
Map registers https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/map-registers).  As for me  ConfigInfo->MaximumTransferLength =ConfigInfo->NumberOfPhysicalBreaks * adaptExt->info.size_max; 
has a way less meaning than 
ConfigInfo->MaximumTransferLength = ConfigInfo->NumberOfPhysicalBreaks * PAGE_SIZE;

in my understanding. if for some platforms  VIRTIO_BLK_F_SIZE_MAX 
https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html
is not equal to PAGE_SIZE then the special treatment needs to be taken to redesign the entire
DMA /SGList handler in virtio-blk device. Otherwise both quest and host will have the different "vision" of
what the DMA is.
If the info.size_max is going to be hardcoded at the qemu side and passed to a guest as a constant, 
then what is the reason to do it at all?

Best regards,
Vadim.

**Comment by icessspark** [comment]
"the qemu part. was it submitted upstream and accepted by virtio-blk maintainers? I personally have some doubts about these changes but this part needs to be reviewed by qemu community."
-> No. But this "size-max" configure change should be abosolely allowed under Virtio 1.1 regulations. And actually QEMU just works fun except that the iov len is not what we expected.

"How it is going to work in the case when adaptExt->info.seg_max == queueLength - 1 ? did you check this condition?
What are the performance results?"
-> The conditions may not be absolutely right since we cannot test them by ourselves. This patch is just an experimental attempt to restore the support of VIRTIO_BLK_F_SEG_MAX and VIRTIO_BLK_F_SIZE_MAX. To the best of my understanding, when backends offered these features, most frontends could accept and handle it properly(Linux, etc). And the potential performance loss came from improper `seg_max` should be considered by backend developers instead. 

"If the info.size_max is going to be hardcoded at the qemu side and passed to a guest as a constant,
then what is the reason to do it at all?"
-> Actually, we are not familiar with Windows driver development. And all we need is that when the backend provides `size_max`, every len in iovs should be no greater than size_max. To fix that, We track the source code and stuck at `StorPortGetScatterGatherList` which we believe deciding the length of elements in sglist.

**Comment by vrozenfe** [comment]
@icessspark 

Sorry for delay in response. 
Just want to fix this issue now, but have some questions to you.
What is your vision of size_max? 
Technically it should be the maximum segment size for a single
dma transaction and should be bigger or equal to one memory 
page size, right?
If so, then ConfigInfo->NumberOfPhysicalBreaks just needs be normalized
according to the  size_max size and seg_max (roughly something like 
size_max * seg_max / PAGE_SIZE)
Does that sound right?

Thanks,
Vadim.
