### ISSUE TITLE
multi queue is enabled, but no effect

### ISSUE THREAD

**Issue by wywself** [virtio-win/kvm-guest-drivers-windows#846]
Hi， 

I used iperf to do network performance test on windows 2016 datacenter vm which has 8 vcpu and enabled mq， compared with sq , the result is similer，compared with disable mq，the result is also similer. My configuration is as follows, if there is any problem, please point it out, thanks.

the way to enable mq and disable mq in windows as shown below:
![image](https://user-images.githubusercontent.com/8843053/196646814-3df7af00-c347-4fa0-a8a6-5a75f8e12d29.png)

the way to set sq as show below:
![image](https://user-images.githubusercontent.com/8843053/196647506-1635945f-971c-4bc3-ada7-43c5ec5b1cba.png)

and the vm xml nic multi queue config as follows:
![image](https://user-images.githubusercontent.com/8843053/196647779-354a1ec5-23a6-4370-bde8-e43374daf14c.png)

version info:
iperf server: centos7.6, 4C8G 
iperf client1：centos7.6，8C16G，iperf-2.0.13
iperf client2：windows 2016 datacenter，8C16G， iperf-2.1.8
virtio-win: virtio-win-0.1.221-1

**Comment by YanVugenfirer** [comment]
Hi @wywself,

Can you post the numbers? Is it transmit or receive performance?

Also, what is your host configuration? Could be that there is single queue already due to host config and in any case when comparing performance of single queue to multi-queue, I suggest to change the setting on the host side.


Example of MQ configuration on the host side (4 queues):
```
-netdev tap,id=hostnet0,vhost=on,....,queues=4 \
-device virtio-net-pci,netdev=hostnet0,....,mq=on,vectors=10 \
```

Best  regards,
Yan.

**Comment by YanVugenfirer** [comment]
Also,  please pay attention that there are several conditions for the MQ usage:

1. Configured on the host (if MQ is not configured on the host, RSS will be still used. But all the traffic will arrive to single "HW" queue, and then distributed by the driver for the completion in different vCPUs - this is less effective than having actual virtio MQ).
2. Amount of queues that will be used is equal or less to the amount of vCPUS (if you have 2 vCPUs, but defined 8 queues, only 2 will be used)

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
> version info:
> iperf server: centos7.6, 4C8G
> iperf client1：centos7.6，8C16G，iperf-2.0.13
> iperf client2：windows 2016 datacenter，8C16G， iperf-2.1.8
> virtio-win: virtio-win-0.1.221-1

We do not expect too much  improved performance for TX (guest client, external server).
The performance improvements is seen the best on RX path (guest server, external client).

**Comment by wywself** [comment]
windows server 2016 vm is iperf client, is transmit performance.

8 queues vm configuration:
-smp 8,maxcpus=32,sockets=4,cores=8,threads=1
-netdev vhost-user,chardev=charnet0,queues=8,id=hostnet0 
-device virtio-net-pci,mq=on,vectors=18,netdev=hostnet0,id=net0,mac=fa:16:3e:63:bd:20,bus=pci.0,addr=0xe,bootindex=3

1 queues vm configuration:
-smp 8,maxcpus=32,sockets=4,cores=8,threads=1
-netdev vhost-user,chardev=charnet0,id=hostnet0 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=fa:16:3e:63:bd:20,bus=pci.0,addr=0xe,bootindex=3

**Comment by YanVugenfirer** [comment]
Can you please check RX performance? I don't expect much difference for TX performance. Even if the packets will be distributed between the queues for TX.

Also, are you using iprerf's "-P" command line option to use multiple streams?

**Comment by wywself** [comment]
iperf server(8vcpu): iperf -s
iperf client(8vcpu 8queue): iperf -c 192.0.0.25 -P 8 -t 100

![image](https://user-images.githubusercontent.com/8843053/196670619-cada7a0c-6aba-4fac-81ed-4204b38fbc89.png)

**Comment by wywself** [comment]
Hi, @YanVugenfirer,

May I ask which version to support mq from?Or where can I find it? Thank you.

Best regards,
Wei.

**Comment by YanVugenfirer** [comment]
Hi @wywself ,

We support MQ for several years. Best to use the latest drivers.

Best regards,
Yan.

**Comment by YanVugenfirer** [comment]
> iperf server(8vcpu): iperf -s iperf client(8vcpu 8queue): iperf -c 192.0.0.25 -P 8 -t 100
> 
> ![image](https://user-images.githubusercontent.com/8843053/196670619-cada7a0c-6aba-4fac-81ed-4204b38fbc89.png)

Is the server running on the host or external machine? If it is external, what's the network speed between the host and external server?

**Comment by wywself** [comment]
> Is the server running on the host or external machine? If it is external, what's the network speed between the host and external server?

Above picture, the server and client both on the same host, consider that it may be limited by the physical network card in this scenario, so I migrate one of guests to another host.

The latest results are as follows， we can see that the mq is better than sq，but the result of disabling rss is similar to enabling rss,do you have any suggestions?

Best regards,
Wei.

![image](https://user-images.githubusercontent.com/8843053/197098247-af1d7d68-ec8c-4d5c-90a6-87c7bb365a5b.png)

**Comment by YanVugenfirer** [comment]
Hi,

There is historical overview of RSS feature and its relations to virtio multitude feature is here: https://www.youtube.com/watch?v=GP6kSs6vCH8

In general: RSS was developed before virtio-net device supported multi queue. Meaning we can implement RSS and completion of RX packets on different cores, even if there is only one "HW" queue. 
On other hand, if we initialises virtio multiqueue, - the host will clarify the packets to different queues disregarding the setting of the Windows OS.  If RSS is enabled - Windows driver will calculate the hash and if needed reschedule packet completion to the proper vCPU, but if RSS is disables - nothing prevents the driver from completing the packet on the core that received the interrupt (and no time wasted for hash calculation).
In order to prevent such situation, virtio spec was extended in order to receive RSS configuration for OS so the packets will be clarified correctly in the first place. It can be tested by enabling the usage of eBPF for the packet classification in QEMU.

Back to ability to multi-queue usage. In order to use multi-queue you need to:
1. Enable proper amount of virtio queues and vectors (device configuration on the host side)
2. Have proper  amount of vCPUs
3. Configure RSS - in order to be OK with the expectations of Windows OS and in order to pass WHQL certifications. If for some use cases, you think that disabling RSS configuration is beneficial - you can do it from the registry or Device Manager.

Best regards,
Yan.

**Comment by wywself** [comment]
Multi-queue has taken effect, thank you. @YanVugenfirer
