### ISSUE TITLE
How to pass NetKVM test "PrivateCloudSimulator - Device.Network.LAN.10GbOrGreater"? 

### ISSUE THREAD

**Issue by ChendongSun** [virtio-win/kvm-guest-drivers-windows#902]
Hi, I only have one HLK test left for NetKVM in windows  server 2016，i can't find how to pass this test "PrivateCloudSimulator - Device.Network.LAN.10GbOrGreater"?
test always fail on step "create cluster and config S2D"，and then  "S2D setup Storage cluster" fail

**Comment by YanVugenfirer** [comment]
Hi,

Are you working on HW virtio? 

1. If you really want to pass CloudSimulator test, then you need to work on creating the proper setup. It is not a regular Studio + 2 clients setup as for the rest of the tests. Did you create the setup according to the documentation? What is the actual error? 
Primary Node, Other Node 1 ,Other Node 2 Should pass the Validate Cluster Test. The test can be ran manually from the Test Controller before running the PCS test in order to ensure that the topology is fine.
3. But if you are working with paravirtualized virtio-net (device in QEMU), you don't need to pass this test. Ask Microsoft for manual errata. For us it is covered by the following erratum:
Windows Server 2016 and Windows Server 2019: 8072
Windows Server 2022: 5434

Best regards,
Yan.

**Comment by ChendongSun** [comment]
Thank y~
